name: Continuous Integration
run-name: Gradle CI
on:
  workflow_call: # required when creating a reusable workflow
#    inputs:
#      config-path:
#        required: false
#        type: string
#    secrets:
#      token:
#        required: false
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        gradle-version: [8.1.0]


    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          # fix: Looks like building 2x these two steps should be combined with Build with Gradle below
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
      - name: Run the Gradle package task
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
#        with:
           # Can include this if we decide to add our own customized gradle package
#          arguments: -b ci.gradle package

      # dependencies automatically installed by gradle

      - name: Lint code
        run: ./gradlew lint

      - name: Compile Tests
        run: ./gradlew compileDebugAndroidTestKotlin

      - name: Run unit tests
        run: ./gradlew test

      - name: Code coverage
        run: ./gradlew koverhtmlreport

      # Build workflow and save as artifact
      # Gradle will automatically compile Kotlin when running tasks like build. This step explicitly validates Kotlin.
      # If there are Kotlin compile errors, this step will fail and you'll see the compilation issues in the logs.
      - name: Build with Gradle
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          arguments: build --scan
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: build/libs
